-- 테이블들
-- 멤버, 메뉴 목록, 메뉴 상세, 1:1 문의, 
--

-- <CREATE>

CREATE TABLE BR_MEMBER_TBL (
    MEMBER_ID VARCHAR2(20) PRIMARY KEY,
    MEMBER_PWD VARCHAR2(20) NOT NULL,
    MEMBER_NAME VARCHAR2(15) NOT NULL,
    MEMBER_BIRTHDAY DATE NOT NULL,
    MEMBER_GENDER CHAR(6),
    MEMBER_EMAIL VARCHAR2(50),
    MEMBER_PHONE VARCHAR2(11),
    MEMBER_ADDRESS VARCHAR2(150)
);


CREATE TABLE BR_MENU_TBL(
    CATEGORY VARCHAR2(20) NOT NULL,
    MENU_NAME VARCHAR2(50) NOT NULL,
    MENU_PRICE NUMBER NOT NULL,
    MENU_TYPE VARCHAR2(20)
);

CREATE TABLE BR_CUSTOMER_BOARD_TBL (
    CUSTOMER_BOARD_NO NUMBER PRIMARY KEY,
    CUSTOMER_BOARD_SUBJECT VARCHAR2(100) NOT NULL,
    CUSTOMER_BOARD_CONTENT VARCHAR2(1500) NOT NULL,
    CUSTOMER_BOARD_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CUSTOMER_BOARD_WRITER VARCHAR2(20) NOT NULL
);


CREATE TABLE BR_MENU_ICECREAM_TBL(
    CATEGORY VARCHAR2(30) NOT NULL,
    MENU_NAME VARCHAR2(80) NOT NULL
);

CREATE SEQUENCE SEQ_CUSTOMER_BOARD_NO;
--START WITH 1
--INCREMENT BY 1
--MAXVALUE 10000
--NOCYCLE
--NOCACHE;




--<INSERT>


INSERT INTO BR_MENU_ICECREAM_TBL VALUES('아이스크림', '31요거트');
INSERT INTO BR_MENU_ICECREAM_TBL VALUES('아이스크림', '그린티');
INSERT INTO BR_MENU_ICECREAM_TBL VALUES('아이스크림', '레인보우 샤베트');
INSERT INTO BR_MENU_ICECREAM_TBL VALUES('아이스크림', '민트 초콜릿칩');
INSERT INTO BR_MENU_ICECREAM_TBL VALUES('아이스크림', '바람과 함께 사라지다');
INSERT INTO BR_MENU_ICECREAM_TBL VALUES('아이스크림', '베리베리 스트로베리');
INSERT INTO BR_MENU_ICECREAM_TBL VALUES('아이스크림', '슈팅스타');
INSERT INTO BR_MENU_ICECREAM_TBL VALUES('아이스크림', '아몬드 봉봉');
INSERT INTO BR_MENU_ICECREAM_TBL VALUES('아이스크림', '엄마는 외계인');
INSERT INTO BR_MENU_ICECREAM_TBL VALUES('아이스크림', '이상한 나라의 솜사탕');
INSERT INTO BR_MENU_ICECREAM_TBL VALUES('아이스크림', '초코나무 숲');
INSERT INTO BR_MENU_ICECREAM_TBL VALUES('아이스크림', '쿠키 앤 크림');

INSERT INTO BR_MEMBER_TBL VALUES('user02', 'pass02', '이번', '00/05/10', 'M', 'user02@gmail.com', '01022222222', '서울시 동대문구');
INSERT INTO BR_MEMBER_TBL VALUES('user02', 'pass03', '삼번', '93/07/07', 'F', 'user03@naver.com', '01033333333', '부산광역시 해운대구');
INSERT INTO BR_MEMBER_TBL VALUES('user04', 'pass04', '사번', '90/06/17', 'F', 'user04@naver.com', '01044444444', '인천광역시 부천구');
INSERT INTO BR_MEMBER_TBL VALUES('user05', 'pass05', '오번', '04/08/23', 'M', 'user05@gmail.com', '01055555555', '강원도 강릉시 화천군');
INSERT INTO BR_MEMBER_TBL VALUES('user06', 'pass06', '육번', '96/03/06', 'F', 'user06@gmail.com', '01066666666', '서울시 성동구');
INSERT INTO BR_MEMBER_TBL VALUES('user07', 'pass07', '칠번', '98/01/30', 'M', 'user07@naver.com', '01077777777', '제주특별자치도 서귀포시');
INSERT INTO BR_MEMBER_TBL VALUES('user08', 'pass08', '팔번', '94/04/12', 'F', 'user08@daum.net', '01088888888', '서울시 서초구');
INSERT INTO BR_MEMBER_TBL VALUES('user09', 'pass09', '구번', '01/12/04', 'F', 'user09@naver.com', '01099999999', '서울시 서대문구');
INSERT INTO BR_MEMBER_TBL VALUES('user10', 'pass10', '십번', '99/11/18', 'F', 'user10@gmail.com', '01010101010', '전라남도 나주시 나주시');

INSERT INTO BR_CUSTOMER_BOARD_TBL VALUES(SEQ_CUSTOMER_BOARD_NO.NEXTVAL, 'user01의 문의글1', 'user01의 문의글', DEFAULT, 'user01');
INSERT INTO BR_CUSTOMER_BOARD_TBL VALUES(SEQ_CUSTOMER_BOARD_NO.NEXTVAL, 'user01의 문의글2', 'user01의 문의글', DEFAULT, 'user01');
INSERT INTO BR_CUSTOMER_BOARD_TBL VALUES(SEQ_CUSTOMER_BOARD_NO.NEXTVAL, 'user01의 문의글3', 'user01의 문의글', DEFAULT, 'user01');
INSERT INTO BR_CUSTOMER_BOARD_TBL VALUES(SEQ_CUSTOMER_BOARD_NO.NEXTVAL, 'user01의 문의글4', 'user01의 문의글', DEFAULT, 'user01');
INSERT INTO BR_CUSTOMER_BOARD_TBL VALUES(SEQ_CUSTOMER_BOARD_NO.NEXTVAL, 'user01의 문의글5', 'user01의 문의글', DEFAULT, 'user01');
INSERT INTO BR_CUSTOMER_BOARD_TBL VALUES(SEQ_CUSTOMER_BOARD_NO.NEXTVAL, 'user01의 문의글6', 'user01의 문의글', DEFAULT, 'user01');
INSERT INTO BR_CUSTOMER_BOARD_TBL VALUES(SEQ_CUSTOMER_BOARD_NO.NEXTVAL, 'user01의 문의글7', 'user01의 문의글', DEFAULT, 'user01');
INSERT INTO BR_CUSTOMER_BOARD_TBL VALUES(SEQ_CUSTOMER_BOARD_NO.NEXTVAL, 'user01의 문의글8', 'user01의 문의글', DEFAULT, 'user01');



--<SELECT>

SELECT * FROM BR_MEMBER_TBL;
SELECT * FROM BR_MENU_ICECREAM_TBL;
SELECT * FROM BR_CUSTOMER_BOARD_TBL;
SELECT COUNT(*) FROM BR_CUSTOMER_BOARD_TBL;
SELECT * FROM BR_MEMBER_TBL;

SELECT * FROM USER_SEQUENCES;


--<DROP>

DROP TABLE BR_MEMBER_TBL;
DROP TABLE BR_MENU_TBL;
DROP TABLE BR_MENU_ICECREAM_TBL;
DROP TABLE BR_CUSTOMER_BOARD_TBL;

DROP SEQUENCE SEQ_CUSTOMER_BOARD_NO;





SELECT CUSTOMER_BOARD_SUBJECT, CUSTOMER_BOARD_CONTENT, MEMBER_NAME FROM BR_CUSTOMER_BOARD_TBL
INNER JOIN BR_MEMBER_TBL ON CUSTOMER_BOARD_WRITER = MEMBER_ID
WHERE CUSTOMER_BOARD_WRITER = 'user01';


SELECT * FROM(
SELECT ROW_NUMBER() OVER(ORDER BY NOTICE_NO DESC) ROW_NUM, NOTICE_TBL.* FROM NOTICE_TBL)
WHERE ROW_NUM BETWEEN 1 AND 10;



SELECT * FROM (SELECT ROW_NUMBER() OVER(ORDER BY CUSTOMER_BOARD_NO DESC) ROW_NUM, CUSTOMER_BOARD_DATE, CUSTOMER_BOARD_SUBJECT FROM BR_CUSTOMER_BOARD_TBL INNER JOIN BR_MEMBER_TBL ON CUSTOMER_BOARD_WRITER = MEMBER_ID WHERE CUSTOMER_BOARD_WRITER = 'user01');



commit;
rollback;










