CREATE TABLE BR_MEMBER_TBL (
    MEMBER_ID VARCHAR2(20) PRIMARY KEY,
    MEMBER_PWD VARCHAR2(20) NOT NULL,
    MEMBER_NAME VARCHAR2(15) NOT NULL,
    MEMBER_BIRTHDAY DATE NOT NULL,
    MEMBER_GENDER CHAR(6),
    MEMBER_EMAIL VARCHAR2(50),
    MEMBER_PHONE VARCHAR2(11),
    MEMBER_ADDRESS VARCHAR2(150)
);

DROP TABLE BR_MEMBER_TBL;

CREATE TABLE BR_MENU_TBL(
    CATEGORY VARCHAR2(20) NOT NULL,
    MENU_NAME VARCHAR2(50) NOT NULL,
    MENU_PRICE NUMBER NOT NULL,
    MENU_TYPE VARCHAR2(20)
);

SELECT * FROM BR_MEMBER_TBL;

CREATE TABLE BR_CUSTOMOR_BOARD_TBL (
    CUSTOMOR_BOARD_NO NUMBER PRIMARY KEY,
    CUSTOMOR_BOARD_SUBJECT VARCHAR2(100) NOT NULL,
    CUSTOMOR_BOARD_CONTENT VARCHAR2(1500) NOT NULL,
    CUSTOMOR_BOARD_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CUSTOMOR_BOARD_WRITER VARCHAR2(20) NOT NULL
);

SELECT * FROM BR_CUSTOMOR_BOARD_TBL;

DROP TABLE BR_CUSTOMOR_BOARD_TBL;

DROP SEQUENCE SEQ_CUSTOMOR_BOARD_NO;

CREATE SEQUENCE SEQ_CUSTOMOR_BOARD_NO;
--START WITH 1
--INCREMENT BY 1
--MAXVALUE 10000
--NOCYCLE
--NOCACHE;

SELECT * FROM USER_SEQUENCES;

commit;

SELECT EMP_NAME "사원명", DEPT_TITLE "부서명", LOCAL_NAME "지역명", NATIONAL_NAME "국가명"
FROM EMPLOYEE 
LEFT JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
LEFT JOIN LOCATION ON LOCATION_ID = LOCAL_CODE
LEFT JOIN NATIONAL USING(NATIONAL_CODE)
WHERE NATIONAL_CODE IN ('KO', 'JP');

INSERT INTO BR_CUSTOMOR_BOARD_TBL VALUES(SEQ_CUSTOMOR_BOARD_NO.NEXTVAL, '두번째', '으악!!!!!!!!!!!!!!!!', DEFAULT, 'user02');

SELECT CUSTOMOR_BOARD_SUBJECT, CUSTOMOR_BOARD_CONTENT, MEMBER_NAME FROM BR_CUSTOMOR_BOARD_TBL
INNER JOIN BR_MEMBER_TBL ON CUSTOMOR_BOARD_WRITER = MEMBER_ID
WHERE CUSTOMOR_BOARD_WRITER = 'user01';


SELECT * FROM(
SELECT ROW_NUMBER() OVER(ORDER BY NOTICE_NO DESC) ROW_NUM, NOTICE_TBL.* FROM NOTICE_TBL)
WHERE ROW_NUM BETWEEN 1 AND 10;



SELECT * FROM (SELECT ROW_NUMBER() OVER(ORDER BY CUSTOMOR_BOARD_NO DESC) ROW_NUM, CUSTOMOR_BOARD_DATE, CUSTOMOR_BOARD_SUBJECT FROM BR_CUSTOMOR_BOARD_TBL INNER JOIN BR_MEMBER_TBL ON CUSTOMOR_BOARD_WRITER = MEMBER_ID WHERE CUSTOMOR_BOARD_WRITER = 'user01') WHERE ROW_NUM BETWEEN 1 AND 10;

SELECT * FROM BR_CUSTOMOR_BOARD_TBL;
















