-- 테이블들
-- 멤버, 메뉴 목록, 메뉴 상세, 1:1 문의, 

CREATE TABLE BR_MEMBER_TBL (
    MEMBER_ID VARCHAR2(20) PRIMARY KEY,
    MEMBER_PWD VARCHAR2(20) NOT NULL,
    MEMBER_NAME VARCHAR2(15) NOT NULL,
    MEMBER_BIRTHDAY DATE NOT NULL,
    MEMBER_GENDER CHAR(6),
    MEMBER_EMAIL VARCHAR2(50),
    MEMBER_PHONE VARCHAR2(11),
    MEMBER_ADDRESS VARCHAR2(150)
);

DROP TABLE BR_MEMBER_TBL;

CREATE TABLE BR_MENU_TBL(
    CATEGORY VARCHAR2(20) NOT NULL,
    MENU_NAME VARCHAR2(50) NOT NULL,
    MENU_PRICE NUMBER NOT NULL,
    MENU_TYPE VARCHAR2(20)
);

DROP TABLE BR_MENU_TBL;

SELECT * FROM BR_MEMBER_TBL;

CREATE TABLE BR_CUSTOMER_BOARD_TBL (
    CUSTOMER_BOARD_NO NUMBER PRIMARY KEY,
    CUSTOMER_BOARD_SUBJECT VARCHAR2(100) NOT NULL,
    CUSTOMER_BOARD_CONTENT VARCHAR2(1500) NOT NULL,
    CUSTOMER_BOARD_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CUSTOMER_BOARD_WRITER VARCHAR2(20) NOT NULL
);

CREATE TABLE BR_MENU_ICECREAM_TBL(
    CATEGORY VARCHAR2(30) NOT NULL,
    MENU_NAME VARCHAR2(80) NOT NULL
);

INSERT INTO BR_MENU_ICECREAM_TBL VALUES('아이스크림', '31요거트');
INSERT INTO BR_MENU_ICECREAM_TBL VALUES('아이스크림', '그린티');
INSERT INTO BR_MENU_ICECREAM_TBL VALUES('아이스크림', '레인보우 샤베트');
INSERT INTO BR_MENU_ICECREAM_TBL VALUES('아이스크림', '민트 초콜릿칩');
INSERT INTO BR_MENU_ICECREAM_TBL VALUES('아이스크림', '바람과 함께 사라지다');
INSERT INTO BR_MENU_ICECREAM_TBL VALUES('아이스크림', '베리베리 스트로베리');
INSERT INTO BR_MENU_ICECREAM_TBL VALUES('아이스크림', '슈팅스타');
INSERT INTO BR_MENU_ICECREAM_TBL VALUES('아이스크림', '아몬드 봉봉');
INSERT INTO BR_MENU_ICECREAM_TBL VALUES('아이스크림', '엄마는 외계인');
INSERT INTO BR_MENU_ICECREAM_TBL VALUES('아이스크림', '이상한 나라의 솜사탕');
INSERT INTO BR_MENU_ICECREAM_TBL VALUES('아이스크림', '초코나무 숲');
INSERT INTO BR_MENU_ICECREAM_TBL VALUES('아이스크림', '쿠키 앤 크림');

SELECT * FROM BR_MENU_ICECREAM_TBL;


commit;


DROP TABLE BR_MENU_ICECREAM_TBL;

SELECT * FROM BR_CUSTOMER_BOARD_TBL;

DROP TABLE BR_CUSTOMER_BOARD_TBL;

DROP SEQUENCE SEQ_CUSTOMER_BOARD_NO;

CREATE SEQUENCE SEQ_CUSTOMER_BOARD_NO;
--START WITH 1
--INCREMENT BY 1
--MAXVALUE 10000
--NOCYCLE
--NOCACHE;

SELECT * FROM USER_SEQUENCES;

commit;

INSERT INTO BR_CUSTOMER_BOARD_TBL VALUES(SEQ_CUSTOMER_BOARD_NO.NEXTVAL, '12', '222', DEFAULT, 'user02');


SELECT CUSTOMER_BOARD_SUBJECT, CUSTOMER_BOARD_CONTENT, MEMBER_NAME FROM BR_CUSTOMER_BOARD_TBL
INNER JOIN BR_MEMBER_TBL ON CUSTOMER_BOARD_WRITER = MEMBER_ID
WHERE CUSTOMER_BOARD_WRITER = 'user01';


SELECT * FROM(
SELECT ROW_NUMBER() OVER(ORDER BY NOTICE_NO DESC) ROW_NUM, NOTICE_TBL.* FROM NOTICE_TBL)
WHERE ROW_NUM BETWEEN 1 AND 10;



SELECT * FROM (SELECT ROW_NUMBER() OVER(ORDER BY CUSTOMER_BOARD_NO DESC) ROW_NUM, CUSTOMER_BOARD_DATE, CUSTOMER_BOARD_SUBJECT FROM BR_CUSTOMER_BOARD_TBL INNER JOIN BR_MEMBER_TBL ON CUSTOMER_BOARD_WRITER = MEMBER_ID WHERE CUSTOMER_BOARD_WRITER = 'user01');

SELECT * FROM BR_CUSTOMER_BOARD_TBL;


SELECT COUNT(*) FROM BR_CUSTOMER_BOARD_TBL;
SELECT * FROM BR_MEMBER_TBL;

commit;












